### ISSUE TITLE
Some queries about training

### ISSUE THREAD

**Issue by brandleyzhou** [sconlyshootery/FeatDepth#10]
Hi there,

This is a good paper, but I have a small question. When training, a feature network, depth net, pose net are trained at the same time? Or the feature network can be trained separately? Thanks.

**Comment by sconlyshootery** [comment]
In our original work,featurenet was trained separately. But we found it can also be trained jointly with depthnet and posenet, and got close performance with the one trained separately. We provide a config file for joint training, it will consume much more GPU memory.

**Comment by brandleyzhou** [comment]
Thanks for your reply. :-)
