### ISSUE TITLE
Package Dependency Errors

### ISSUE THREAD

**Issue by ArminMasoumian** [sconlyshootery/FeatDepth#11]
Hi, 

I tried to use the environment you uploaded, but I got errors. I tried to Install the packages one by one from requirements.txt file, but the problem is when I install torch=1.2, the mmcv=0.4.4 cannot be install and keep giving an error same as the spatial-correlation-sampler package. however when I tried the last version of torch (1.7v) the mmcv=0.4.4 was installed successfully, but the spatial-correlation-sampler package not.

I tried both Ubuntu and windows 10. Is there any other versions that can be match together so I can try them as well?
Also, did you use both tensorflow and pytorch or only pytorch?

**Comment by sconlyshootery** [comment]
You can skip the installation of spatial-correlation-sampler package, it wasn't used in our codes.

**Comment by sconlyshootery** [comment]
I'm sorry to cause inconvenience for setting up our environment.
I will delete spatial-correlation-sampler package from requirement list.

**Comment by ArminMasoumian** [comment]
> I'm sorry to cause inconvenience for setting up our environment.
> I will delete spatial-correlation-sampler package from requirement list.

Thank you for your reply. Would you please let me know you used Ubuntu or Windows? and which version, so I can setup the same as your setup.

Thank you in advance.

**Comment by sconlyshootery** [comment]
I used Ubuntu 18.04.

**Comment by ArminMasoumian** [comment]
Thank you for your reply.

I set up Ubuntu 18.04 and installed new requirement.txt file and everything is working now.

I just have another questions, I tried to run the code, but it gives me this error "FileNotFoundError: [Errno 2] No such file or directory: '/media/armin/DATA/FeatDepth-master/Models/resnet50.pth'"

I found a resnet50.pth file on the internet and tried to use it but it did not worked and I received new error regarding resnet18.pth. I saw on config code that you used 3 pretrained weights (autoencoder, depth and pose), but on github, only the autoencoder pretrained weights is available to download.

My question is where can I get the other resnet pretrained weighted that's needed for this code "from .resnet import resnet18, resnet34, resnet50, resnet101"

Thank you in advance.

**Comment by adizhol** [comment]
I think the resnets use torchvision pretrained models

**Comment by sconlyshootery** [comment]
you can download resnet pretrained weights from these official links:
  | 'resnet18': 'https://download.pytorch.org/models/resnet18-5c106cde.pth',
  | 'resnet34': 'https://download.pytorch.org/models/resnet34-333f7ec4.pth',
  | 'resnet50': 'https://download.pytorch.org/models/resnet50-19c8e357.pth',
  | 'resnet101': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth',
  | 'resnet152': 'https://download.pytorch.org/models/resnet152-b121ed2d.pth',
  | 'resnext50_32x4d': 'https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth',
  | 'resnext101_32x8d': 'https://download.pytorch.org/models/resnext101_32x8d-8ba56ff5.pth',
  | 'wide_resnet50_2': 'https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth',
  | 'wide_resnet101_2': 'https://download.pytorch.org/models/wide_resnet101_2-32ee1156.pth',
  |

**Comment by ArminMasoumian** [comment]
Thank you
