### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by e2r-htz** [sconlyshootery/FeatDepth#13]
Trying to run using the distributed command as shown in  run.py gives the following error.

`RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).`

**Comment by sconlyshootery** [comment]
It seems that you don't use the same environment as us, you can just follow the instructions to set 'find_unused_parameters=True' in the 'torch.nn.parallel.DistributedDataParallel'.

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/c83d1cf8d06aa85f96e65c92f650ca67c1bfa613/mono/apis/trainer.py#L151
You can change this line to MMDistributedDataParallel(model.cuda(), find_unused_parameters=True)

**Comment by sconlyshootery** [comment]
You can continue discussion in your newly opened issue, I will close this.
