### ISSUE TITLE
Testing Single Image

### ISSUE THREAD

**Issue by ArminMasoumian** [sconlyshootery/FeatDepth#14]
Hi,

is there any code available to just run a single image and get the depth of the image as an output?
I tried to use and modify infer.py for that, but it seems code will collect the input from kitti raw dataset and it cannot be changed.

Thank you in advance.

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/c83d1cf8d06aa85f96e65c92f650ca67c1bfa613/scripts/infer.py#L23
If your image come from kitti dataset, you can just revise the val_file here to only other images.
Or you can load a single image, let input[('color',0,0)]=image.cuda(), and feed input into model, like
<img width="1111" alt="截屏2020-11-20 上午11 10 58的副本" src="https://user-images.githubusercontent.com/15374408/99753613-7e6e3900-2b21-11eb-8bae-97b1e0bf2442.png">

**Comment by ArminMasoumian** [comment]
> https://github.com/sconlyshootery/FeatDepth/blob/c83d1cf8d06aa85f96e65c92f650ca67c1bfa613/scripts/infer.py#L23
> 
> 
> If your image come from kitti dataset, you can just revise the val_file here to only other images.
> Or you can load a single image, let input[('color',0,0)]=image.cuda(), and feed input into model, like
> <img alt="截屏2020-11-20 上午11 10 58的副本" width="1111" src="https://user-images.githubusercontent.com/15374408/99753613-7e6e3900-2b21-11eb-8bae-97b1e0bf2442.png">

Thank you for the code, but I didn't understand exactly, do I need to modify this code inside infer.py code, or need to write the new code from scratch, load the model and single image from outside the kitti dataset, and use these example you provide to test it?

**Comment by sconlyshootery** [comment]
Did you fix your problem, can I close this issue now?

**Comment by ArminMasoumian** [comment]
> Did you fix your problem, can I close this issue now?

Thank you for the code, but I didn't understand exactly, do I need to modify this code inside infer.py code, or need to write the new code from scratch, load the model and single image from outside the kitti dataset, and use these example you provide to test it?

**Comment by sconlyshootery** [comment]
import numpy as np
import torch
import cv2
import time
import os
from PIL import Image

from model.registry import MONO

MIN_DEPTH=1e-3
MAX_DEPTH=80

class MapVisualizer(object):
    def __init__(self, cfg, model_path, scale):
        model = MONO.module_dict[cfg.model['name']](cfg.model)
        checkpoint = torch.load(model_path)
        try:
            model.load_state_dict(checkpoint['state_dict'], strict=True)
        except:
            print('unable to load weights strictly, turn to load unstrictly')
            model.load_state_dict(checkpoint['state_dict'], strict=False)
        self.model = model.cuda().eval()
        self.cfg = cfg
        self.scale = scale

    def __transform(self, cv2_img):
        im_tensor = torch.from_numpy(cv2_img.astype(np.float32)).cuda().unsqueeze(0)
        im_tensor = im_tensor.permute(0, 3, 1, 2).contiguous()
        im_tensor = torch.nn.functional.interpolate(im_tensor, [self.cfg['HEIGHT'], self.cfg['WIDTH']],mode='bilinear', align_corners=False)
        im_tensor /= 255
        return im_tensor

    def predict(self, cv2_img):
        original_height, original_width = cv2_img.shape[:2]
        im_tensor = self.__transform(cv2_img)

        with torch.no_grad():
            input = {}
            input['color_aug', 0, 0] = im_tensor
            outputs = self.model(input)

        disp = outputs[("disp", 0, 0)]
        disp_resized = torch.nn.functional.interpolate(disp, (original_height, original_width), mode="bilinear", align_corners=False)
        min_disp = 1/self.cfg.model['max_depth']
        max_disp = 1/self.cfg.model['min_depth']
        depth = 1/(disp_resized.squeeze().cpu().numpy()*max_disp + min_disp) * self.scale
        return depth, disp_resized.squeeze().cpu().numpy()

**Comment by sconlyshootery** [comment]
You only need to modify inside infer.py, you need to replace loading images via dataloader by using the code I provided above.

**Comment by ArminMasoumian** [comment]
I modified infer.py and use the provided code to load the image, I don't receive any error and it print "Done", but in the saving directory shows nothing, either input image or depth of the image, folder is epmty. Maybe I did something wrong in the code, here is the modified code of infer.py : 
`from __future__ import absolute_import, division, print_function
import os
import cv2
import sys
import matplotlib.pyplot as plt
import numpy as np
from mmcv import Config

import torch
from torch.utils.data import DataLoader
image = "/media/armin/DATA/FeatDepth-master/test1/2.jpg" 

sys.path.append('.')
from mono.model.registry import MONO
from mono.model.mono_baseline.layers import disp_to_depth
from mono.datasets.utils import readlines
from mono.datasets.kitti_dataset import KITTIRAWDataset

cv2.setNumThreads(0)  # This speeds up evaluation 5x on our unix systems (OpenCV 3.3.1)



def evaluate(cfg_path,model_path,gt_path, output_path):
    cv2_img = cv2.imread(image)
    cfg = Config.fromfile(cfg_path)

    dataset = KITTIRAWDataset(cfg.data['in_path'],
                              cv2_img,
                              cfg.data['height'],
                              cfg.data['width'],
                              [0],
                              is_train=False,
                              gt_depth_path=gt_path)

    def __transform(self, cv2_img):
        im_tensor = torch.from_numpy(cv2_img.astype(np.float32)).cuda().unsqueeze(0)
        im_tensor = im_tensor.permute(0, 3, 1, 2).contiguous()
        im_tensor = torch.nn.functional.interpolate(im_tensor, [self.cfg['HEIGHT'], self.cfg['WIDTH']],mode='bilinear', align_corners=False)
        im_tensor /= 255
        return im_tensor

    def predict(self, cv2_img):
        original_height, original_width = cv2_img.shape[:2]
        im_tensor = self.__transform(cv2_img)

        cfg.model['imgs_per_gpu'] = 1
        model = MONO.module_dict[cfg.model['name']](cfg.model)
        checkpoint = torch.load(model_path)
        model.load_state_dict(checkpoint['state_dict'], strict=False)
        model.cuda()
        model.eval()

        with torch.no_grad():
            input = {}
            input['color_aug', 0, 0] = im_tensor
            outputs = self.model(input)

        disp = outputs[("disp", 0, 0)]
        disp_resized = torch.nn.functional.interpolate(disp, (original_height, original_width), mode="bilinear", align_corners=False)
        min_disp = 1/self.cfg.model['max_depth']
        max_disp = 1/self.cfg.model['min_depth']
        depth = 1/(disp_resized.squeeze().cpu().numpy()*max_disp + min_disp) * self.scale
        return depth, disp_resized.squeeze().cpu().numpy()
        img_path = os.path.join(output_path, 'img_{:0>4d}.jpg'.format(batch_idx))
        plt.imsave(img_path, inputs[("color", 0, 0)][0].squeeze().transpose(0,1).transpose(1,2).cpu().numpy())
        pred_disp, _ = disp_to_depth(disp, 0.1, 100)
        pred_disp = pred_disp[0, 0].cpu().numpy()
        pred_disp = cv2.resize(pred_disp, (cfg.data['width'], cfg.data['height']))

        img_path = os.path.join(output_path, 'disp_{:0>4d}.jpg'.format(batch_idx))
        vmax = np.percentile(pred_disp, 95)
        plt.imsave(img_path, pred_disp, cmap='magma', vmax=vmax)

    print("\n-> Done!")


if __name__ == "__main__":
    cfg_path = '/media/armin/DATA/FeatDepth-master/config/cfg_kitti_fm.py'# path to cfg file
    model_path = '/media/armin/DATA/FeatDepth-master/test1/fm_depth.pth'# path to model weight
    gt_path = '/media/armin/DATA/FeatDepth-master/mono/datasets/gt_depths.npz' # path to kitti gt depth
    output_path = '/media/armin/DATA/FeatDepth-master/2' # dir for saving depth maps
    if not os.path.exists(output_path):
        os.mkdir(output_path)
    evaluate(cfg_path,model_path,gt_path,output_path)`

**Comment by ArminMasoumian** [comment]
I modified infer.py and use the provided code to load the image, I don't receive any error and it print "Done", but in the saving directory shows nothing, either input image or depth of the image, folder is epmty. Maybe I did something wrong in the code, here is the modified code of infer.py :

from __future__ import absolute_import, division, print_function
import os
import cv2
import sys
import matplotlib.pyplot as plt
import numpy as np
from mmcv import Config

import torch
from torch.utils.data import DataLoader
image = "/media/armin/DATA/FeatDepth-master/test1/2.jpg" 

sys.path.append('.')
from mono.model.registry import MONO
from mono.model.mono_baseline.layers import disp_to_depth
from mono.datasets.utils import readlines
from mono.datasets.kitti_dataset import KITTIRAWDataset

cv2.setNumThreads(0)  # This speeds up evaluation 5x on our unix systems (OpenCV 3.3.1)



def evaluate(cfg_path,model_path,gt_path, output_path):
    cv2_img = cv2.imread(image)
    cfg = Config.fromfile(cfg_path)

    dataset = KITTIRAWDataset(cfg.data['in_path'],
                              cv2_img,
                              cfg.data['height'],
                              cfg.data['width'],
                              [0],
                              is_train=False,
                              gt_depth_path=gt_path)

    def __transform(self, cv2_img):
        im_tensor = torch.from_numpy(cv2_img.astype(np.float32)).cuda().unsqueeze(0)
        im_tensor = im_tensor.permute(0, 3, 1, 2).contiguous()
        im_tensor = torch.nn.functional.interpolate(im_tensor, [self.cfg['HEIGHT'], self.cfg['WIDTH']],mode='bilinear', align_corners=False)
        im_tensor /= 255
        return im_tensor

    def predict(self, cv2_img):
        original_height, original_width = cv2_img.shape[:2]
        im_tensor = self.__transform(cv2_img)

        cfg.model['imgs_per_gpu'] = 1
        model = MONO.module_dict[cfg.model['name']](cfg.model)
        checkpoint = torch.load(model_path)
        model.load_state_dict(checkpoint['state_dict'], strict=False)
        model.cuda()
        model.eval()

        with torch.no_grad():
            input = {}
            input['color_aug', 0, 0] = im_tensor
            outputs = self.model(input)

        disp = outputs[("disp", 0, 0)]
        disp_resized = torch.nn.functional.interpolate(disp, (original_height, original_width), mode="bilinear", align_corners=False)
        min_disp = 1/self.cfg.model['max_depth']
        max_disp = 1/self.cfg.model['min_depth']
        depth = 1/(disp_resized.squeeze().cpu().numpy()*max_disp + min_disp) * self.scale
        return depth, disp_resized.squeeze().cpu().numpy()
        img_path = os.path.join(output_path, 'img_{:0>4d}.jpg'.format(batch_idx))
        plt.imsave(img_path, inputs[("color", 0, 0)][0].squeeze().transpose(0,1).transpose(1,2).cpu().numpy())
        pred_disp, _ = disp_to_depth(disp, 0.1, 100)
        pred_disp = pred_disp[0, 0].cpu().numpy()
        pred_disp = cv2.resize(pred_disp, (cfg.data['width'], cfg.data['height']))

        img_path = os.path.join(output_path, 'disp_{:0>4d}.jpg'.format(batch_idx))
        vmax = np.percentile(pred_disp, 95)
        plt.imsave(img_path, pred_disp, cmap='magma', vmax=vmax)



    print("\n-> Done!")


if __name__ == "__main__":
    cfg_path = '/media/armin/DATA/FeatDepth-master/config/cfg_kitti_fm.py'# path to cfg file
    model_path = '/media/armin/DATA/FeatDepth-master/test1/fm_depth.pth'# path to model weight
    gt_path = '/media/armin/DATA/FeatDepth-master/mono/datasets/gt_depths.npz' # path to kitti gt depth
    output_path = '/media/armin/DATA/FeatDepth-master/2' # dir for saving depth maps
    if not os.path.exists(output_path):
        os.mkdir(output_path)
    evaluate(cfg_path,model_path,gt_path,output_path)

**Comment by sconlyshootery** [comment]
you should not use dataloader, the function 'predict' is enough.

**Comment by ArminMasoumian** [comment]
Sorry I am new in this topic, I run this code:

`import os
import cv2
import sys
import numpy as np
import torch
import time
from PIL import Image
from mono.model.registry import MONO


image = "/media/armin/DATA/FeatDepth-master/test1/2.jpg" 
cv2_img = cv2.imread(image)

MIN_DEPTH = 1e-3
MAX_DEPTH = 80

class MapVisualizer(object):
    def init(self,cfg,model_path,scale):
        model = MONO.module_dict[cfg.model['name']](cfg.model)
        checkpoint = torch.load(model_path)
        try:
            model.load_state_dict(checkpoint['state_dict'], strict=True)
        except:
            print('unable to load weights strictly, turn to load unstrictly')
            model.load_state_dict(checkpoint['state_dict'], strict=False)
            self.model = model.cuda().eval()
            self.cfg = cfg
            self.scale = scale

    def __transform(self, cv2_img):
        im_tensor = torch.from_numpy(cv2_img.astype(np.float32)).cuda().unsqueeze(0)
        im_tensor = im_tensor.permute(0, 3, 1, 2).contiguous()
        im_tensor = torch.nn.functional.interpolate(im_tensor, [self.cfg['HEIGHT'], self.cfg['WIDTH']],mode='bilinear', align_corners=False)
        im_tensor /= 255
        return im_tensor

    def predict(self, cv2_img):
        original_height, original_width = cv2_img.shape[:2]
        im_tensor = self.__transform(cv2_img)

        with torch.no_grad():
            input = {}
            input['color_aug', 0, 0] = im_tensor
            outputs = self.model(input)

            disp = outputs[("disp", 0, 0)]
            disp_resized = torch.nn.functional.interpolate(disp, (original_height, original_width), mode="bilinear", align_corners=False)
            min_disp = 1/self.cfg.model['max_depth']
            max_disp = 1/self.cfg.model['min_depth']
            depth = 1/(disp_resized.squeeze().cpu().numpy()*max_disp + min_disp) * self.scale
            return depth, disp_resized.squeeze().cpu().numpy()


#if __name__ == "__main__":
    cfg_path = '/media/armin/DATA/FeatDepth-master/config/cfg_kitti_fm.py'# path to cfg file
    model_path = '/media/armin/DATA/FeatDepth-master/test1/fm_depth.pth'# path to model weight
    gt_path = '/media/armin/DATA/FeatDepth-master/mono/datasets/gt_depths.npz' # path to kitti gt depth
    output_path = '/media/armin/DATA/FeatDepth-master/2' # dir for saving depth maps
    if not os.path.exists(output_path):
        os.mkdir(output_path)
    init(cfg_path,model_path,gt_path,output_path)`



I got the this error:

`Traceback (most recent call last):
  File "2.py", line 17, in <module>
    class MapVisualizer(object):
  File "2.py", line 61, in MapVisualizer
    init(cfg_path,model_path,gt_path,output_path)
  File "2.py", line 19, in init
    model = MONO.module_dict[cfg.model[fm_depth.pth]](cfg.model)
AttributeError: 'str' object has no attribute 'model'
`

**Comment by sconlyshootery** [comment]
Recently I will write codes for single image inference, I will notice youwhen I release.

**Comment by sconlyshootery** [comment]
You can this function "scripts/infer_singleimage.py" to infer a single image

**Comment by ArminMasoumian** [comment]
Thank you for uploading code for testing single image, although when I ran the code, this error appear: 

`Traceback (most recent call last):
  File "/media/armin/DATA/anaconda3/envs/test/lib/python3.7/site-packages/torch/serialization.py", line 308, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1.py", line 76, in <module>
    evaluate(cfg_path, model_path, img_path, output_path)
  File "1.py", line 53, in evaluate
    model = MONO.module_dict[cfg.model['name']](cfg.model)
  File "/media/armin/DATA/FeatDepth-master/mono/model/mono_fm/net.py", line 37, in __init__
    self.opt.extractor_pretrained_path)
  File "/media/armin/DATA/FeatDepth-master/mono/model/mono_fm/net.py", line 17, in build_extractor
    checkpoint = torch.load(pretrained_path, map_location='cpu')
  File "/media/armin/DATA/anaconda3/envs/test/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/media/armin/DATA/anaconda3/envs/test/lib/python3.7/site-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/media/armin/DATA/anaconda3/envs/test/lib/python3.7/site-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/media/armin/DATA/anaconda3/envs/test/lib/python3.7/site-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/media/armin/DATA/anaconda3/envs/test/lib/python3.7/site-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.`

**Comment by sconlyshootery** [comment]
It seems that  a wrong image path or other path is given, causing nothing is loaded.
You can print some variables to debug your program.

**Comment by ArminMasoumian** [comment]
Thank you so much, it works now
