### ISSUE TITLE
Perceptual loss is only in one scale

### ISSUE THREAD

**Issue by adizhol** [sconlyshootery/FeatDepth#18]
https://github.com/sconlyshootery/FeatDepth/blob/c83d1cf8d06aa85f96e65c92f650ca67c1bfa613/mono/model/mono_fm_joint/net.py#L115

shouldn't the "perceptual loss" be calculated on the features in each scale?

**Comment by adizhol** [comment]
sorry, the features are calculate only on the "0" scale. So my remark is wrong.

But you can move this calculation outside the scale loop (after the feature projection) and remove the len(scale) division.

**Comment by adizhol** [comment]
Sorry for re-opening, but why do you calculate the minimum perceptional losses of the same scale?

**Comment by sconlyshootery** [comment]
I used largest feature map for perceptional loss calculation, since it is spatially finer and semantically weaker, which means it is more likely to distinguish two close points. 
And I tried to use multiple feature maps for perceptional loss, but I found little improvement.

**Comment by adizhol** [comment]
That's what I thought :)
Thank you

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you are welcome to reopen it.
