### ISSUE TITLE
Generate_features_pred room for optimization?

### ISSUE THREAD

**Issue by rvarun7777** [sconlyshootery/FeatDepth#2]
In the Generate_features_pred function as pointed below:
https://github.com/sconlyshootery/FeatDepth/blob/3b5bf793bd075c390c18b3c22777a860444e6851/mono/model/mono_fm/net.py#L80

I see that you are using only the scale 0 features. But the calculation takes place for all the 4 scales.
I believe, it can be calculated only once.
https://github.com/sconlyshootery/FeatDepth/blob/3b5bf793bd075c390c18b3c22777a860444e6851/mono/model/mono_fm/net.py#L168
https://github.com/sconlyshootery/FeatDepth/blob/3b5bf793bd075c390c18b3c22777a860444e6851/mono/model/mono_fm/net.py#L184

**Comment by sconlyshootery** [comment]
Yes, you're right, thank you for your advice.
________________________________
发件人: Varun Ravikumar <notifications@github.com>
发送时间: 2020年9月11日 21:14:04
收件人: sconlyshootery/FeatDepth
抄送: Subscribed
主题: [美团安全提示：疑似营销邮件] [sconlyshootery/FeatDepth] Generate_features_pred room for optimization? (#2)


In the Generate_features_pred as pointed with the below line
https://github.com/sconlyshootery/FeatDepth/blob/3b5bf793bd075c390c18b3c22777a860444e6851/mono/model/mono_fm/net.py#L80

I see that you are using only the scale 0 features. But the calculation takes place for all the 4 scales.
I believe, it can be calculated only once.
https://github.com/sconlyshootery/FeatDepth/blob/3b5bf793bd075c390c18b3c22777a860444e6851/mono/model/mono_fm/net.py#L168
https://github.com/sconlyshootery/FeatDepth/blob/3b5bf793bd075c390c18b3c22777a860444e6851/mono/model/mono_fm/net.py#L184

―

**Comment by sconlyshootery** [comment]
Yes, you're right, thank you for your advice.
