### ISSUE TITLE
OSError: [Errno 95] Operation not supported: 'epoch_1.pth' -> ...

### ISSUE THREAD

**Issue by anonymoustbd** [sconlyshootery/FeatDepth#21]
I find an answer "some environments do not support  os.symlink  so that you can add an argument in the checkpoint_config field in config files, like checkpoint_config=dict(create_symlink=False)" in mmdetection project. However, when i set like that, models (epoch_n.pth) can not be saved, which could result in failing to evaluate and compute metrics.

**Comment by sconlyshootery** [comment]
I find declaration of runner in MMCV, I find that turning off create_symlink button will not stop saving checkpoint, you can debug into save_checkpoint function to find whether the checkpoint is saved correctly.
![image](https://user-images.githubusercontent.com/15374408/101450142-05664280-3965-11eb-96be-da74dd885153.png)

**Comment by anonymoustbd** [comment]
It works! I ignored the two lines you selected. Thanks for your help again!
