### ISSUE TITLE
batch_size for eval_depth when add post_process

### ISSUE THREAD

**Issue by xuwanpeng12** [sconlyshootery/FeatDepth#22]
First of all, thank you for your amazing paper！
I set IMGS_PER_GPU = 6, workers_per_gpu = 4，training model on 4 gpus. When I evaluation my model adding post_process as monodepth2, I got "RuntimeError: Caught RuntimeError in DataLoader worker process 1." and "RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 370 and 374 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:612"
Traceback (most recent call last):
  File "/home/pp/python/FeatDepth/scripts/eval_depth.py", line 128, in <module>
    evaluate(MODEL_PATH, CFG_PATH, GT_PATH)
  File "/home/pp/python/FeatDepth/scripts/eval_depth.py", line 61, in evaluate
    for batch_idx, inputs in enumerate(dataloader):
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 370 and 374 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:612

Traceback (most recent call last):
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/pp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/pp/anaconda3/envs/pytorch/bin/python3.7', '-u', '/home/pp/python/FeatDepth/scripts/eval_depth.py', '--local_rank=0']' returned non-zero exit status 1.

I think this is caused by the batch-size setting. The batch-size when I train the model is equal to 24, right?
    dataloader = DataLoader(dataset,
                            2,
                            shuffle=False,
                            num_workers=4,
                            pin_memory=True,
                            drop_last=False)
To apply post_process, batch-size must be an integral multiple of 2, so I did not find a suitable value.
If I want to successfully adding post_process for evaluation, how can I solve this problem?
Looking forward to your recovery, thank you very much！

**Comment by sconlyshootery** [comment]
Got 370 and 374 in dimension 1 indicates the input image sizes are not the same.
Since our dataset will resize images to the same size, please make sure this resizing step is conducted.
You can test on only one GPU to see error information, otherwise you will be difficult to locate the bug.

**Comment by xuwanpeng12** [comment]
When I set the batch_size of input images to 1 as default, there is no problem. Does this mean that it is not the size of the input image?
But setting it to 2 or others will not work. The num_works even set 0 or -1 doesn't work.

**Comment by sconlyshootery** [comment]
I understood, you can set drop_last=True in the dataloader to avoid this problem.
This problem is very difficult to detect， it occurs when the number of input images can not be divided exactly by the batchsize, set drop_last=True will drop out reminder.

**Comment by xuwanpeng12** [comment]
Thank you for your kind words, I will try it again.
There is another problem,  what dose checkpoint_path = '/node01_data5/monodepth2-test/model/refine/smallfigure.pth' means in cfg_cityscape.py.  I can not find "smallfigure.pth" in monodepth2. How is it trained?

**Comment by xuwanpeng12** [comment]
Can you succeed? when set drop_last=True in the dataloader.
I load the model you provided without any changes, and set drop_last=True, batch_size still cannot be set to any value other than 1. I found that the problem lies in the process of the "for batch_idx, inputs in enumerate(dataloader):" loop, which is neither the beginning nor the end. Is the thread having a problem with batch allocation?

Second，in cfg_cityscape.py 
gt_depth_path = '/node01_data5/monodepth2-test/monodepth2/gt_depths.npz'
checkpoint_path = '/node01_data5/monodepth2-test/model/refine/smallfigure.pth'
The cityscapes dataset is not used in monodepth2, here GT using KITTI?
and "checkpoint_path = '/node01_data5/monodepth2-test/model/refine/smallfigure.pth'"Where to get the model？

Thank you for your prompt reply, and sorry for the delay in your precious study time.

**Comment by sconlyshootery** [comment]
For the first problem, the setting does not work,because in here:
https://github.com/sconlyshootery/FeatDepth/blob/4d42fe283fce917a4d862a0d1a9b6ddade1b70f7/scripts/eval_depth.py#L41
The img_per_gpu is set to 1, so the model can only receive one image at a time, you can set it to be equal to your batchsize.

For the second problem, it is my negligence that cfg_cityscape is not updated, this version can not be used, I will update as soon as possible, before that you can use other cfgs (the cfgs for kitti have been tested) .

**Comment by xuwanpeng12** [comment]
I have carefully revised all the things you mentioned, but they are not working.
I found that set num_workers=0, "RuntimeError: Caught RuntimeError in DataLoader worker process 1" will disappear. But as long as batch is not equal to 1, "RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 370 and 374 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:612" will always there.I even found a single-GPU computer test that didn't work.
I think this is related to your packaging of "depth and pose" into one ".pth" file, because "depth" requires one image and "pose" requires two images.

Second, The "doom" data set is only used to evaluate the pose. It does not need cfg_autoencoder.py? and "extractor_pretrained_path" in cfg_odom_fm.py comes from kitti_raw's "cfg_kitti_autoencoder.py" training model?

**Comment by xuwanpeng12** [comment]
If I want to store all models separately like monodepth2, and each epoch is stored in a folder, how can I modify it?

**Comment by sconlyshootery** [comment]
You may release your codes to make me convenient to find the problem, I will debug it on my device.

1) num_works can not be set to 0, otherwise there will be no thread assigned for current job; 
2) when evaluating depth, posenet is not used, so the way of packing checkpoints may not cause the problem;
3) I don't know 'doom' dataset refer to which dataset;
4) when evaluating, only current module (depthnet or posenet alone) is needed to load corresponding pretrained weights, others are not needed; 
5) Changing the storation of checkpoints is difficult for current framework, it is conducted automatically via MMCV.

**Comment by xuwanpeng12** [comment]
Thank you very much for your kind help.

eval_depth.py

from __future__ import absolute_import, division, print_function
import cv2
import sys
import numpy as np
from mmcv import Config

import torch
from torch.utils.data import DataLoader

sys.path.append('.')
from mono.model.registry import MONO
from mono.model.mono_baseline.layers import disp_to_depth
from mono.datasets.utils import readlines, compute_errors
from mono.datasets.kitti_dataset import KITTIRAWDataset

cv2.setNumThreads(0)  # This speeds up evaluation 5x on our unix systems (OpenCV 3.3.1)
STEREO_SCALE_FACTOR = 36
MIN_DEPTH=1e-3
MAX_DEPTH=80

def batch_post_process_disparity(l_disp, r_disp):
    """Apply the disparity post-processing method as introduced in Monodepthv1
    """
    _, h, w = l_disp.shape
    m_disp = 0.5 * (l_disp + r_disp)
    l, _ = np.meshgrid(np.linspace(0, 1, w), np.linspace(0, 1, h))
    l_mask = (1.0 - np.clip(20 * (l - 0.05), 0, 1))[None, ...]
    r_mask = l_mask[:, :, ::-1]
    return r_mask * l_disp + l_mask * r_disp + (1.0 - l_mask - r_mask) * m_disp

def evaluate(MODEL_PATH, CFG_PATH, GT_PATH):
    filenames = readlines("/home/pp/python/FeatDepth2/mono/datasets/splits/exp/val_files.txt")
    cfg = Config.fromfile(CFG_PATH)

    dataset = KITTIRAWDataset(cfg.data['in_path'],
                              filenames,
                              cfg.data['height'],
                              cfg.data['width'],
                              [0],
                              is_train=False,
                              gt_depth_path=GT_PATH)

    dataloader = DataLoader(dataset,
                            2,
                            shuffle=False,
                            num_workers=4,
                            pin_memory=True,
                            drop_last=True)

    cfg.model['imgs_per_gpu'] = 2
    model = MONO.module_dict[cfg.model['name']](cfg.model)
    checkpoint = torch.load(MODEL_PATH)
    model.load_state_dict(checkpoint['state_dict'], strict=True)
    model.cuda()
    model.eval()

    pred_disps = []
    with torch.no_grad():
        for batch_idx, inputs in enumerate(dataloader):
            for key, ipt in inputs.items():
                inputs[key] = ipt.cuda()
            outputs = model(inputs)

            disp = outputs[("disp", 0, 0)]
            # N = pred_disp.shape[0] // 2
            # pred_disp = batch_post_process_disparity(pred_disp[:N], pred_disp[N:, :, ::-1])
            pred_disp, _ = disp_to_depth(disp, 0.1, 100)
            pred_disp = pred_disp.cpu()[:, 0].numpy()
            pred_disps.append(pred_disp)
    pred_disps = np.concatenate(pred_disps)

    gt_depths = np.load(GT_PATH, allow_pickle=True, fix_imports=True, encoding='latin1')["data"]

    print("-> Evaluating")
    if cfg.data['stereo_scale']:
        print('using baseline')
    else:
        print('using mean scaling')

    errors = []
    ratios = []
    for i in range(pred_disps.shape[0]):
        gt_depth = gt_depths[i]
        gt_height, gt_width = gt_depth.shape[:2]

        pred_disp = pred_disps[i]
        pred_disp = cv2.resize(pred_disp, (gt_width, gt_height))

        pred_depth = 1 / pred_disp

        mask = np.logical_and(gt_depth > MIN_DEPTH, gt_depth < MAX_DEPTH)
        crop = np.array([0.40810811 * gt_height, 0.99189189 * gt_height,
                         0.03594771 * gt_width,  0.96405229 * gt_width]).astype(np.int32)
        crop_mask = np.zeros(mask.shape)
        crop_mask[crop[0]:crop[1], crop[2]:crop[3]] = 1
        mask = np.logical_and(mask, crop_mask)

        pred_depth = pred_depth[mask]
        gt_depth = gt_depth[mask]

        ratio = np.median(gt_depth) / np.median(pred_depth)
        ratios.append(ratio)

        if cfg.data['stereo_scale']:
            ratio = STEREO_SCALE_FACTOR

        pred_depth *= ratio
        pred_depth[pred_depth < MIN_DEPTH] = MIN_DEPTH
        pred_depth[pred_depth > MAX_DEPTH] = MAX_DEPTH
        errors.append(compute_errors(gt_depth, pred_depth))

    ratios = np.array(ratios)
    med = np.median(ratios)
    mean_errors = np.array(errors).mean(0)
    print("Scaling ratios | med: {:0.3f} | std: {:0.3f}".format(med, np.std(ratios / med)))
    print("\n" + ("{:>}| " * 7).format("abs_rel", "sq_rel", "rmse", "rmse_log", "a1", "a2", "a3"))
    print(("&{:.3f} " * 7).format(*mean_errors.tolist()) + "\\\\")
    print("\n-> Done!")


if __name__ == "__main__":
    CFG_PATH = '/home/pp/python/FeatDepth2/config/cfg_kitti_fm.py'#path to cfg file
    GT_PATH = '/home/pp/python/FeatDepth2/gt_depths.npz'#path to kitti gt depth
    MODEL_PATH = '/home/pp/python/FeatDepth2/tmp/fm_depth.pth'#path to model weights
    evaluate(MODEL_PATH, CFG_PATH, GT_PATH)

cfg_kitti_fm.py

DEPTH_LAYERS = 50#resnet50
POSE_LAYERS = 18#resnet18
FRAME_IDS = [0, -1, 1, 's']#0 refers to current frame, -1 and 1 refer to temperally adjacent frames, 's' refers to stereo adjacent frame.
IMGS_PER_GPU = 1 #the number of images fed to each GPU
HEIGHT = 320#input image height
WIDTH = 1024#input image width

data = dict(
    name = 'kitti',#dataset name
    split = 'exp',#training split name
    height = HEIGHT,
    width = WIDTH,
    frame_ids = FRAME_IDS,
    in_path = '/home/pp/guazai/KITTI',#path to raw data
    gt_depth_path = '/home/pp/python/FeatDepth2/gt_depths.npz',#path to gt data
    png = True,#image format
    stereo_scale = True if 's' in FRAME_IDS else False,
)

model = dict(
    name = 'mono_fm',# select a model by name
    depth_num_layers = DEPTH_LAYERS,
    pose_num_layers = POSE_LAYERS,
    frame_ids = FRAME_IDS,
    imgs_per_gpu = IMGS_PER_GPU,
    height = HEIGHT,
    width = WIDTH,
    scales = [0, 1, 2, 3],# output different scales of depth maps
    min_depth = 0.1, # minimum of predicted depth value
    max_depth = 100.0, # maximum of predicted depth value
    depth_pretrained_path = '/home/pp/python/FeatDepth2/resnet{}.pth'.format(DEPTH_LAYERS),# pretrained weights for resnet
    pose_pretrained_path =  '/home/pp/python/FeatDepth2/resnet{}.pth'.format(POSE_LAYERS),# pretrained weights for resnet
    extractor_pretrained_path = '/home/pp/python/FeatDepth2/autoencoder.pth',# pretrained we
    automask = False if 's' in FRAME_IDS else True,
    disp_norm = False if 's' in FRAME_IDS else True,
    perception_weight = 1e-3,
    smoothness_weight = 1e-3,
)

# resume_from = '/node01_data5/monodepth2-test/model/ms/ms.pth'#directly start training from provide weights
resume_from = None
finetune = None
total_epochs = 40
imgs_per_gpu = IMGS_PER_GPU
learning_rate = 1e-4
workers_per_gpu = 4
validate = True

optimizer = dict(type='Adam', lr=learning_rate, weight_decay=0)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[20,30],
    gamma=0.5,
)

checkpoint_config = dict(interval=1)
log_config = dict(interval=50,
                  hooks=[dict(type='TextLoggerHook'),])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
workflow = [('train', 1)]

I hardly changed any settings, the loaded models are all provided by you. But if I want to use post-process, batch-size must be an integer multiple of 2. I cannot achieve it.
It only works when batch-size is equal to 1.

![Screenshot from 2020-12-13 17-10-44](https://user-images.githubusercontent.com/63273800/102008048-ab9cb880-3d68-11eb-8a90-9209affc2f17.png)

Second, The "odom" data set is only used to evaluate the pose. It does not need cfg_autoencoder.py? and "extractor_pretrained_path" in cfg_odom_fm.py comes from kitti_raw's "cfg_kitti_autoencoder.py" training model?

**Comment by sconlyshootery** [comment]
OK, I solved the problem, the bug is not coming from the loading of images, it is from loading gt_depth in the dataloader, you can solve it by set gt_depth_path=None in the KITTIRAWDataset in evaluate function.

(1)Yes, it doesn't need cfg_autoencoder.py; 
(2)Yes, it comes from kitti_raw's "cfg_kitti_autoencoder.py" training model.

**Comment by xuwanpeng12** [comment]
You are so amazing！ I learned a lot from the discussion with you, and Looking forward to your cfg_cityscape updatade.
Thank you very very much! and then I will closed the comment.
