### ISSUE TITLE
wtat is gt_depths.npz and how can i get it

### ISSUE THREAD

**Issue by Asherchi** [sconlyshootery/FeatDepth#25]

**Comment by ruili3** [comment]
you can check the code of Monodepth2. a file named maybe 'export_depth_gt.py'

**Comment by Asherchi** [comment]
ok,thanks for you reply

**Comment by Asherchi** [comment]
> you can check the code of Monodepth2. a file named maybe 'export_depth_gt.py'

ok, thanks for you reply

**Comment by sconlyshootery** [comment]
Like the advise provided above, you can refer to monodepth2 for data preparation https://github.com/sconlyshootery/monodepth2.
