### ISSUE TITLE
A conda issue and An error when running the code of config file 'cfg_kitti_fm_joint'

### ISSUE THREAD

**Issue by ruili3** [sconlyshootery/FeatDepth#26]
Hi, thanks for your brilliant work. I'm planning to run the code but encountered two issues.

1) Conda environment. The readme.md file and requirements.txt say the pytorch version should be >1.2，but I downloaded the provided py37t11.tar.gz conda env file and found the torch version is 1.1.0. So I wonder what is the right version of the required pytorch.

2) I use pytorch 1.7.1 and torchvision 0.8.2 to run the code. I choose to jointly train the depth network and the autoencoder using cfg file 'cfg_kitti_fm_joint.py' with resolution 192x640, and I change the path in the file to my server's setting. When running the code, an error occurs 

'  File "FeatDepth/mono/model/mono_fm_joint/layers.py", line 59, in forward
    cam_points = depth.view(self.batch_size, 1, -1) * cam_points
RuntimeError: The size of tensor a (61440) must match the size of tensor b (122880) at non-singleton dimension 2'  

I check the code and find the reason may lied in the inconsistent batchsize between 'depth' and 'cam_points'. Could you give me some guidance to settle this error? Thank you very much!

**Comment by sconlyshootery** [comment]
We courage to use >1.2, but 1.1 is also capable.
Did you load pretrained weights that trained on kitti, if in this case, you have to keep the img_per_gpu in cfg to be equal to our setttings.
The batsize of each component is all controlled by the img_per_gpu variable, so make sure they are consistent.

**Comment by ruili3** [comment]
I intend to train the model from scratch using 'cfg_kitti_fm_joint.py' (resume_from = None). To this end, I only change the 'depth_pretrained_path ' and 'pose_pretrained_path' to load the pretrained resnet model (resnet-18 and resnet-50) from pytorch.org. The rest paremeters are kept with the initial settings (including IMGS_PER_GPU = 2). Is that the right way to launch the script?

**Comment by ruili3** [comment]
> We courage to use >1.2, but 1.1 is also capable.
> Did you load pretrained weights that trained on kitti, if in this case, you have to keep the img_per_gpu in cfg to be equal to our setttings.
> The batsize of each component is all controlled by the img_per_gpu variable, so make sure they are consistent.

Problem solved. I download your conda environment and it works. It seems to be the library version issue.
