### ISSUE TITLE
Batch size issue

### ISSUE THREAD

**Issue by ruili3** [sconlyshootery/FeatDepth#27]
Hi there, I found the parameter IMGS_PER_GPU varies in different .cfg file (=1 in cfg_kitti_fm.py and =2 in cfg_kitti_fm_joint.py). As the batchsize you mentioned in the paper is 2 (on 8 GPU), does that mean there are 2 training sample on each GPU and the total batchsize is 16? 
I wonder how should I set the right batchsize (IMGS_PER_GPU and number of GPUs) so as to get the desired result on Monocular KITTI (0.104 0.729 4.481 0.179 0.893 0.965 0.984) ?
Thank you very much!

**Comment by sconlyshootery** [comment]
Yes, our paper means here are 2 training sample on each GPU and the total batchsize is 16.
IMGS_PER_GPU=2 is used in our paper to get the performance, but I don't whether it is the best setting.

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you can reopen it.
