### ISSUE TITLE
how can i get weight/resnet/resnet50.pth

### ISSUE THREAD

**Issue by zsj19977777zsj** [sconlyshootery/FeatDepth#28]

**Comment by genius-hl** [comment]
Hello,I have the problem too.Could you tell me how to find the file? Thank you!

**Comment by zsj19977777zsj** [comment]
Here is it,you can find it in monodepyh2,change the code to resnet50;can&nbsp;Automatically&nbsp;download&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sconlyshootery/FeatDepth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 上午9:20
***@***.***&gt;;
抄送:&nbsp;" ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [sconlyshootery/FeatDepth] how can i get weight/resnet/resnet50.pth (#28)





 
Hello,I have the problem too.Could you tell me how to find the file? Thank you!
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

resnet50.pth (97.75M, 2021年05月12日 09:31 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7739653633c1d1ca1282450e1531001c530103070303030a1b5c5654011c06525058480e0555051e0e0855500705010552090352333d3241534a0b534704021d464d0d360e&code=69e63123

**Comment by genius-hl** [comment]
> Here is it,you can find it in monodepyh2,change the code to resnet50;can&nbsp;Automatically&nbsp;download&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sconlyshootery/FeatDepth" ***@***.***&gt;; 发送时间:&nbsp;2021年4月12日(星期一) 上午9:20 ***@***.***&gt;; 抄送:&nbsp;" ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [sconlyshootery/FeatDepth] how can i get weight/resnet/resnet50.pth (#28) Hello,I have the problem too.Could you tell me how to find the file? Thank you! — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 从QQ邮箱发来的超大附件 resnet50.pth (97.75M, 2021年05月12日 09:31 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7739653633c1d1ca1282450e1531001c530103070303030a1b5c5654011c06525058480e0555051e0e0855500705010552090352333d3241534a0b534704021d464d0d360e&code=69e63123

Thank you for your help!
