### ISSUE TITLE
Cityscapes 

### ISSUE THREAD

**Issue by vinx-2105** [sconlyshootery/FeatDepth#29]
How can I train on Cityscapes dataset?

**Comment by sconlyshootery** [comment]
We provide cfg name cfg_cityscape for training on cityscape, and a dataloader for cityscape in mono/datasets/cityscape_dataset.py.
You can utilize them for training on cityscape.

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you can reopen it.
