### ISSUE TITLE
Relationship between Pose(s-->t) and Pose(t-->s) 

### ISSUE THREAD

**Issue by anonymoustbd** [sconlyshootery/FeatDepth#30]
When obtaining Pose(s-->t) (batch-size is B*6) predicted from PoseNet, whether it‘s possible to compute Pose(t-->s) directly?

**Comment by sconlyshootery** [comment]
Your question is similar with this issue https://github.com/sconlyshootery/FeatDepth/issues/9#issue-728989322.
You may find answer above.
Please inform me if you have further question.

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you can reopen it.
