### ISSUE TITLE
Question about weight between featuremetric and photometric

### ISSUE THREAD

**Issue by WilhelmT** [sconlyshootery/FeatDepth#31]
Hello, I have a question about your implementation

When running your code I see that perception_loss (featuremetric) is 0.000. The likely culprit here is that in the config it's specified that the weight the loss is modified by (for feature-metric only) is 0.001. Meaning that feature-metric loss is a thousand times smaller in magnitude then photo-metric. Is this intended?

Thank you

**Comment by sconlyshootery** [comment]
Here the value is rounded to only 4 decimals, more decimals will be seen by setting number of digits.
And feature-metric loss is not designed toreplace photometric loss but is supposed to compensate the short-comings of smoothness loss, so its weight is equal to smoothness weight.

**Comment by sconlyshootery** [comment]
If no further question, I will close this issue. 
You can reopen this question, if you want to ask.
