### ISSUE TITLE
Number of GPUs and performance

### ISSUE THREAD

**Issue by WilhelmT** [sconlyshootery/FeatDepth#32]
Hi,

I'm wondering if the performance will be affected if I do not have access to 8 gpus like in your paper (apart from longer training times of course). Are the weights updated asynchronously over the different gpus?

Thank you

**Comment by sconlyshootery** [comment]
No, weights  are updated synchronously over the different gpus. I haven't tried training on other configurations, so I am not sure whether the performance will be promised.
