### ISSUE TITLE
Performance on NYUv2?

### ISSUE THREAD

**Issue by rxqy** [sconlyshootery/FeatDepth#33]
Hi, thanks for sharing the code.
I'm quite interested in the performance on NYUv2. Did you follow a similar setting as in kitti?
 I found you only released the model on NYU but not the cfg files or dataloaders.

**Comment by sconlyshootery** [comment]
Yes, I only provide a pretrained model, since I trained the model during my internship last year.
Now I don't have NYU data at hand, it is difficult for me to rewrite a dataloader for NYU.
NYU dataloader is analogous with that of Kitti, you may try to write following the kitti dataloader.
