### ISSUE TITLE
Problems on image reconstruction

### ISSUE THREAD

**Issue by Wenchao-Du** [sconlyshootery/FeatDepth#35]
why do you use the sigmoid function in decoder.py for final image reconstruction ? and the loss functions also use the reprojection loss instead of general L1 and L2 loss. Is there anything behind it ?

**Comment by sconlyshootery** [comment]
1) sigmoid is used to output values ranging from 0 ~ 1, since input image values are also normalized to 0~1.
2) the loss is composed of l1 and ssim, the introduction of ssim will emphasize more on the similarity within a small local region rather than only on pixel level.
