### ISSUE TITLE
About the training of the autoencoder

### ISSUE THREAD

**Issue by Rodger-Huang** [sconlyshootery/FeatDepth#37]
Hi, I want to know why the `dis` is set as 0?
https://github.com/sconlyshootery/FeatDepth/blob/83506218188e96557c8bf9360b12d84d2c89f733/config/cfg_kitti_autoencoder.py#L36

**Comment by sconlyshootery** [comment]
It is the setting I used for ablation study, I'm sorry to forget to reset it for normal training, I'll update it.
