### ISSUE TITLE
How can I turn off saving the log files

### ISSUE THREAD

**Issue by ArminMasoumian** [sconlyshootery/FeatDepth#38]
I want to remove saving the log file and log.json file and only save the epoch.pth files after each epoch is done, because this saving log files after each batch, take a lot of my cpu usage and that makes a pc crash.
I tried to find where is the torch.save command, but I could not find it.

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/db7344ae9d9cefafc92983fc8c5b30920751be68/config/cfg_kitti_fm.py#L62
You can let hooks=[] to turn off log saving.

**Comment by ArminMasoumian** [comment]
> [dict(type='TextLoggerHook'),])

Tnx it worked.

**Comment by ArminMasoumian** [comment]
Hi,

I turned off the log file, but still the PC will be frozen after 30 minutes when I run the code. I think the data loader use CPU for loading the images every-time for loading them instead of GPU, but I am not sure.

Is there anyway to reduce the CPU usage? I am trying to run mono-fm config on kitty dataset and I have only 1 GPU (GTX 1080 Ti).

I was monitoring the CPU and GPU  while the code was running, the GPU temperature and usage is fine (around 60 °C and 51% memory), However, the CPU memory is low around 11% but the usage go high to 161%.

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/db7344ae9d9cefafc92983fc8c5b30920751be68/config/cfg_kitti_fm.py#L46
you can reduce the number of threads here to reduce CPU usage, and note that this number must be bigger than 0.

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you are welcome to reopen it.
