### ISSUE TITLE
Pre-training

### ISSUE THREAD

**Issue by ArnavVarma** [sconlyshootery/FeatDepth#42]
Hi,

A doubt regarding the ResNets.

The original monodepth2 uses ImageNet pre-trained weights as initialisation for the ResNets, but it is not entirely clear to me if the paper results for FeatDepth were obtained with or without pre-training.

**Comment by sconlyshootery** [comment]
The model weights are initialized with ImageNet pretrained weights.

**Comment by sconlyshootery** [comment]
The use of resnet version is not limited to 18 or 50, it depends on what kind of computational resource you have, you can choose other versions according to your need. Higher version usually provide better performance.

**Comment by sconlyshootery** [comment]
I will close this issue, if you have further question, you can reopen it.
