### ISSUE TITLE
Backpropagation

### ISSUE THREAD

**Issue by cocacola0** [sconlyshootery/FeatDepth#43]
How does the backpropagation work? Can you point out the piece of code responsible for the backpropagation?

**Comment by sconlyshootery** [comment]
It is achieved by built-in functions of MMCV, you can delve into code here to figure out.
https://github.com/sconlyshootery/FeatDepth/blob/db7344ae9d9cefafc92983fc8c5b30920751be68/mono/apis/trainer.py#L155

**Comment by sconlyshootery** [comment]
I will close this issue, you can reopen it if you have further question.
