### ISSUE TITLE
perceptional_loss in scale loop

### ISSUE THREAD

**Issue by Darknesszlx** [sconlyshootery/FeatDepth#44]
https://github.com/sconlyshootery/FeatDepth/blob/db7344ae9d9cefafc92983fc8c5b30920751be68/mono/model/mono_fm_joint/net.py#L114-L121

https://github.com/sconlyshootery/FeatDepth/blob/db7344ae9d9cefafc92983fc8c5b30920751be68/mono/model/mono_fm_joint/net.py#L175-L178

perceptional_loss is only computed in scale [1] (1/2 w, 1/2 h),  but the code block is in the scale loop. So I think the loss is summed 5 times, and / len(self.opt.scales) at last.

**Comment by sconlyshootery** [comment]
Yes, the code written in this way is convenient for me to test perceptional loss' effect under different scale. I found it works best at largest scale, so I fixed scale here.

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/issues/18#issuecomment-785796082
A similar issue I answered recently, you can refer to it.

**Comment by sconlyshootery** [comment]
I will close this issue now, if you have further question, please reopen it.
