### ISSUE TITLE
inference results in your Table 2 in your paper

### ISSUE THREAD

**Issue by sunnyHelen** [sconlyshootery/FeatDepth#45]
Hi, thanks for your great work. I am a little confused about the test results reported in your Table 2. Why the results of DORN and BTS are much worse than that in their papers? Are the test splits used in their papers are different with yours and monodepth2? Please help me to figure it out.
Looking forward to your reply~ Thanks a lot~

**Comment by sconlyshootery** [comment]
The number is from Table 2 in BTS paper, which is its version 4. 
The link is https://arxiv.org/pdf/1907.10326v4.pdf.
Since BTS paper has been through 5 versions, and its content changes a lot, so you must refer to its old version to find the number.

**Comment by sunnyHelen** [comment]
In BTS's latest version there is a huge difference regarding to the test results of DORN and their own results. Maybe there's something wrong in the old version. It's too confusing.

**Comment by sconlyshootery** [comment]
When I writed this paper, BTS is at version 4, I have no idea about the upcoming change.
Since the BTS' code is released, there is a way to test its authenticity.

**Comment by sunnyHelen** [comment]
I don't know. Maybe there are different test splits or using different ground truth version. Too confusing~ Most paper cited DORN's results as 0.072, but in some papers it is a little worse.

**Comment by sconlyshootery** [comment]
I will close this issue, you can reopen it if you have further question.
