### ISSUE TITLE
Change of scale for intrinsic parameters on the commit "update some settings

### ISSUE THREAD

**Issue by WilhelmT** [sconlyshootery/FeatDepth#46]
Hello,

I noticed that a few weeks ago you updated the repository and the matrix K for the intrinsic parameters is now scaled accordingly to the image-size of the output of your autoencoder (half of the original image).

Was thing change present when you generated your results as provided in your article?

Thanks

**Comment by sconlyshootery** [comment]
The setting is changed due to the inconsistency between remote and local version of our codes, the pre-trained weights are trained according to local version, the commit is only used to keep the consistency between them. This commit doesn't affect the results in our paper.

**Comment by sconlyshootery** [comment]
I will close this issue, you can reopen it if you have further question.
