### ISSUE TITLE
How to choose featurenet when training separately?

### ISSUE THREAD

**Issue by MeLonJ10** [sconlyshootery/FeatDepth#48]
Hi, it a exciting job offering a novel loss.
I have a quetion about featurenet. In your original paper, featurenet is trained separately. How do one choose a featurenet to serve for following training of depthNet and poseNet? Is there any metric?
Thank you so much！

**Comment by sconlyshootery** [comment]
As we said in the paper, the featurenet has to produce features which are discriminative and have a wide convergence basin. 
Any architetcture like ResNet, DenseNet, HRnet trained with proposed loss---discriminative loss and convergent loss can be used as featurenet.

**Comment by MeLonJ10** [comment]
Thanks for the reply, but there is still doubt.
When traning a featurenet, one could store its weight at different epoches. And how to choose the best weight to restore at following traning of posenet and depthnet? According to the loss value?
Thank you so much!

**Comment by sconlyshootery** [comment]
According to the loss on the test set.

**Comment by MeLonJ10** [comment]
Thanks!
