### ISSUE TITLE
about feature visualization (PCA)

### ISSUE THREAD

**Issue by MeLonJ10** [sconlyshootery/FeatDepth#49]
It's a wonderful job!
I am confused about feture visualization. (Fig.3 in you paper).
You said that one principle channel was selected using PCA decomposition. Did you mean, for example, the first channel of 64-channel feature map?
May you describle more detailedly?
Thank you so much!

**Comment by sconlyshootery** [comment]
When you use PCA function provided by a python library, it will tell which channel is the principle channel, you can use the channel for visualization.

**Comment by sconlyshootery** [comment]
I will close this issue for now, if you have further question, you can reopen it.
