### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by genius-hl** [sconlyshootery/FeatDepth#50]
Hello,Does the path in the code need to be changed to my own path?Maybe my question is very low level,but when i run the command `python run.py`,many errors were reported.I am confused about the true command to execute the programe.Thanks for your help!

**Comment by sconlyshootery** [comment]
Please read instruction in readme carefully.

**Comment by sconlyshootery** [comment]
import sys
sys.path.append('.')
sys.path.append('..')


you can use above codes to avoid such a situation.
