### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by Penitto** [sconlyshootery/FeatDepth#51]
Hi! I'm curious about pretrained weights and configs: which config was used to receive [this](https://drive.google.com/file/d/1HlAubfuja5nBKpfNU3fQs-3m3Zaiu9RI/view?usp=sharing) and which for [this](https://drive.google.com/file/d/1CfCtz55s4QHya3y3UslxsuD_0cxNlA-D/view?usp=sharing). I guess it `cfg_kitti_fm.py` and `cfg_kitti_fm_refine.py` respectively. Am I right?

**Comment by Penitto** [comment]
And what is the main difference between `resume_from` and `finetune` configs in your code?

**Comment by sconlyshootery** [comment]
> Hi! I'm curious about pretrained weights and configs: which config was used to receive [this](https://drive.google.com/file/d/1HlAubfuja5nBKpfNU3fQs-3m3Zaiu9RI/view?usp=sharing) and which for [this](https://drive.google.com/file/d/1CfCtz55s4QHya3y3UslxsuD_0cxNlA-D/view?usp=sharing). I guess it `cfg_kitti_fm.py` and `cfg_kitti_fm_refine.py` respectively. Am I right?

Yes, you are right, the name of config corresponds with that of ckpt. Kitti refer to training data, fm refer to model, refine refer to online refinement.

**Comment by Penitto** [comment]
> > And what is the main difference between `resume_from` and `finetune` configs in your code?
> 
> The resume_from mode will reload pretrained weights and will continue the unfinished training.
> If the training is finished, the resume_from mode will not continue training.
> While finetune mode will training from the very beginning.

So if I want to train pretrained on kitti weights with cityscapes dataset, I have to use `finetune` parameter? Or I can change `total_epochs` and `data` in config?

**Comment by sconlyshootery** [comment]
The two ways will work the same, but I suggest you to use the finetune mode.

**Comment by Penitto** [comment]
Okay. Thank you a lot!
