### ISSUE TITLE
Can you please provide the depth visualization results of eigen test set？image or .npy both ok~

### ISSUE THREAD

**Issue by sunnyHelen** [sconlyshootery/FeatDepth#52]
Can you please provide the depth visualization results of eigen test set？image or .npy both ok~ I would like to cite your paper, and compare the visualization result with yours.

**Comment by sconlyshootery** [comment]
I store them in google drive, you can download it from this link:
https://drive.google.com/file/d/1RYRVqsOzfrrT8wLFWFF_bp8f5yMBDPNj/view?usp=sharing
BTW, you can use scripts/infer_singleimage.py to generate visualized depth prediction.

**Comment by sunnyHelen** [comment]
Thanks a lot. What's the version of model of these visualization results? M, M*, MS or MS*?

**Comment by sconlyshootery** [comment]
MS

**Comment by sunnyHelen** [comment]
Thank you very much. Could you please provide your test results of monocular model (abs rel 0.104) in .npy？Because I need visualization images in different color mode~
