### ISSUE TITLE
_make_crp

### ISSUE THREAD

**Issue by wangcong607** [sconlyshootery/FeatDepth#55]
Hello,
First，thanks for your contributions. But I have a question about the function of _make_crp in your depth_deocoder.  
In the code, you use the sequence of four 1*1 convolutions, so I want to know why?
Thanks for your reply.

**Comment by sconlyshootery** [comment]
The architecture is modified from a lightweight structure used in segmentation named "Light-weight RefineNet".
1 * 1 convs is used to save memory,  you can extend it to 3 * 3 convs will obtain better performance.
