### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by JIEMIN1995** [sconlyshootery/FeatDepth#57]
Thanks for sharing good project! 
two questions.
1. I notice u don't modify intrinsics (center_x) while doing flip. Not sure whether it matters.
2. Have u tried other geometric augmentations such as random scale and crop? Not sure whether it helps.

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/64128b03873b27ffa5e99a5cb1712dd8aa15cb0d/mono/datasets/mono_dataset.py#L178
Flipping is done here.
Random scale is not suitable for this task, it will affect the networks' judgement for real-world scale.

**Comment by JIEMIN1995** [comment]
baseline_sign flip the baseline of extrinsics while training stereo, but doesn't change intrinsics.
for example, a normalized 3x3 intrinsic matrix [[fx, 0, cx], [0, fy, cy], [0, 0, 1]], after fliping, convert to [[fx, 0, 1-cx], [0, fy, cy], [0, 0, 1]]

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/64128b03873b27ffa5e99a5cb1712dd8aa15cb0d/mono/model/mono_fm/net.py#L159
Changing the transformation between frames will work the same.

**Comment by JIEMIN1995** [comment]
Thanks a lot.
