### ISSUE TITLE
_make_crp

### ISSUE THREAD

**Issue by wangcong607** [sconlyshootery/FeatDepth#58]
Thanks for your reply.
I have read something about  "Light-weight RefineNet". This method using 1*1 instead of 3*3. But I don't know the reason for using four successive 1*1 convolutions. So why use four times instead of one? 
Thanks

**Comment by sconlyshootery** [comment]
The 1\*1 conv is used to replace 3\*3 conv to follow pooling.
The iteration will enlarge the receptive field of the network.
This architecture doesn't bring improvement, just use the normal conv3*3 should be all right.
