### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pjckoch** [sconlyshootery/FeatDepth#6]
Hi,

I'm very interested in your work and would like to re-use some of it for my master's thesis. Would you be able to provide a license file, please?

Thanks in advance!

Best,
Patrick

**Comment by sconlyshootery** [comment]
I add a MIT License in our project, I hope it will meet your needs.

**Comment by pjckoch** [comment]
Perfect, thank you so much!

**Comment by zshn25** [comment]
Hi @sconlyshootery, your [mono_dataset](https://github.com/sconlyshootery/FeatDepth/blob/master/mono/datasets/mono_dataset.py) and some other files look exactly same as from [monodepth2](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py). Is the license for these files also MIT License?

**Comment by sconlyshootery** [comment]
No, the license for monodepth2 is not MIT license, so please follow the license monodepth2 use when use the these files.

________________________________
发件人: Zeeshan Khan Suri <notifications@github.com>
发送时间: 2020年11月20日 17:09:39
收件人: sconlyshootery/FeatDepth
抄送: 舒畅; Mention
主题: [美团安全提示：疑似营销邮件] Re: [sconlyshootery/FeatDepth] License (#6)


Hi @sconlyshootery<https://github.com/sconlyshootery>, your mono_dataset<https://github.com/sconlyshootery/FeatDepth/blob/master/mono/datasets/mono_dataset.py> and some other files look exactly same as from monodepth2<https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py>. Is the license for these files also MIT License?

―
