### ISSUE TITLE
saving reconstructed image

### ISSUE THREAD

**Issue by ArminMasoumian** [sconlyshootery/FeatDepth#60]
Hi,

is there anyway to save the reconstructed image? I need it to add in my paper.

Thank you in advance

**Comment by sconlyshootery** [comment]
https://github.com/sconlyshootery/FeatDepth/blob/550420b3fb51a027549716b74c6fbce41651d3a5/mono/model/mono_baseline/net.py#L134
save the result from above line will work

**Comment by sconlyshootery** [comment]
You can reopen this issue when you have further problem.
