### ISSUE TITLE
pretrained weights for resnet

### ISSUE THREAD

**Issue by zyx-zx** [sconlyshootery/FeatDepth#61]
Where can I find the weights of resnet pre-training?

**Comment by Klutch0615** [comment]
Owner
sconlyshootery commented on 16 Nov 2020 • 
you can download resnet pretrained weights from these official links:
  | 'resnet18': 'https://download.pytorch.org/models/resnet18-5c106cde.pth',
  | 'resnet34': 'https://download.pytorch.org/models/resnet34-333f7ec4.pth',
  | 'resnet50': 'https://download.pytorch.org/models/resnet50-19c8e357.pth',
  | 'resnet101': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth',
  | 'resnet152': 'https://download.pytorch.org/models/resnet152-b121ed2d.pth',
  | 'resnext50_32x4d': 'https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth',
  | 'resnext101_32x8d': 'https://download.pytorch.org/models/resnext101_32x8d-8ba56ff5.pth',
  | 'wide_resnet50_2': 'https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth',
  | 'wide_resnet101_2': 'https://download.pytorch.org/models/wide_resnet101_2-32ee1156.pth',
