### ISSUE TITLE
Question about overall famework (Fig.1 in paper)

### ISSUE THREAD

**Issue by bei181** [sconlyshootery/FeatDepth#63]
Thank you for releasing the codes of such amazing work!

However, I am confused about the framework. As shown in Fig.1 in your paper, the depth map is predicted on every source frame. In the codes, you only predict the depth map on the target frame. Is there a mistake on the figure? I draw a new figure as below according to my understandings.

![image](https://user-images.githubusercontent.com/36898451/127105778-2cd5bbf3-2377-46c9-99f8-74216afcf74b.png)

Looking forward to your feedback! Thanks.

**Comment by sconlyshootery** [comment]
Yes, your understanding is correct, our figure is confusing.

**Comment by sconlyshootery** [comment]
You can reopen this issue when you have further problem.
