### ISSUE TITLE
Problems with the color_aug process

### ISSUE THREAD

**Issue by Klutch0615** [sconlyshootery/FeatDepth#64]
First of all, thank you for your contribution to this!

I'm having some problems reproducing your code and would like to ask you a question if you're handy!

I was training with my own training dataset and an error occurred, which I show below.

`File "/home/zhangsr/anaconda3/envs/featdepth/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhangsr/workspace/FeatDepth-master/mono/datasets/mono_dataset.py", line 171, in __getitem__
    self.preprocess(inputs, color_aug)
  File "/home/zhangsr/workspace/FeatDepth-master/mono/datasets/mono_dataset.py", line 96, in preprocess
    inputs[(n + "_aug", im, i)] = self.to_tensor(color_aug(f))
TypeError: 'tuple' object is not callable`

Did some problem arise in the process of data augmentation, making it possible to turn function methods into tuple form?

I would be grateful if I could get your answer!

**Comment by sconlyshootery** [comment]
Thank you for jenaer's contribution.
