### ISSUE TITLE
About ground truth pose

### ISSUE THREAD

**Issue by sunnyHelen** [sconlyshootery/FeatDepth#65]
https://github.com/sconlyshootery/FeatDepth/blob/64128b03873b27ffa5e99a5cb1712dd8aa15cb0d/mono/datasets/kitti_dataset.py#L100
Hi, thanks for sharing the great work. I'd like to ask why the ground truth pose is represented by only three numbers.

**Comment by sconlyshootery** [comment]
Here, only translation is considered.

**Comment by sunnyHelen** [comment]
Ok, got it. Then, how can we get the ground truth rotation？For Kitti odometry dataset, we can get it from the provided pose.txt, right? Is there anyway to get ground truth pose for Kitti raw dataset?

**Comment by sconlyshootery** [comment]
You need to refer to codes from https://github.com/sconlyshootery/packnet-sfm to compute gt pose from raw data.

**Comment by sconlyshootery** [comment]
You can reopen this issue when you have further problem.
