### ISSUE TITLE
Evaluate with NYU dataset

### ISSUE THREAD

**Issue by konstihengge** [sconlyshootery/FeatDepth#67]
Hello,
thanks for sharing the code.
I would like to evaluate your method with the NYU dataset.
Can you provide the code for it?
When it is not possible, how can i write it.
Did you follow a similar setting as in the kitti code?

**Comment by sconlyshootery** [comment]
you can revise this file to load NUY dataset and train on it. https://github.com/sconlyshootery/FeatDepth/blob/550420b3fb51a027549716b74c6fbce41651d3a5/mono/datasets/folder_dataset.py

**Comment by sconlyshootery** [comment]
You can reopen this issue when you have further problem.
