### ISSUE TITLE
Is there a way to visually check the output of the FeatureNet

### ISSUE THREAD

**Issue by Kletterer** [sconlyshootery/FeatDepth#74]
Hi,
Thanks for the great paper! I am interested in the FeatureNet as I am writing my master thesis about monocular depth estimation.

Testing the depth-map works great using the infer.py script, but is there a way to save the output of the encoder part of the FeatureNet? Similar to Fig. 3 in the paper?

Warm regards!

**Comment by sconlyshootery** [comment]
You can use PCA decomposition to find 3 channels for visualization as a rgb image, you can also save the maximum along the channels to get one channel image.
