### ISSUE TITLE
Question about MS evaluation

### ISSUE THREAD

**Issue by AttackonMuggle** [sconlyshootery/FeatDepth#75]
Thank you for the pre-trained model and test code.
I just find that when evaluate the model trained by MS, if I use ratio like this, it will get better results than STEREO_SCALE_FACTOR.
https://github.com/sconlyshootery/FeatDepth/blob/550420b3fb51a027549716b74c6fbce41651d3a5/scripts/eval_depth.py#L91
But in your config, you set stereo_scale = True if 's' in FRAME_IDS else False. Can you explain why you set it that way?

**Comment by sconlyshootery** [comment]
We do this for mono because the scale is ambiguous, we use this operation to find a best matched scale to compare with GT, but for stereo, baseline is known, still using this operation will be unfair to compare with other stereo methods.

**Comment by sconlyshootery** [comment]
Unsupervised Learning of Depth and Ego-Motion from Video
this paper may help you get a better understanding of this setting.

**Comment by AttackonMuggle** [comment]
Thanks for your reply, and I have another question. Have you trained this code with only stereo data?  My test results are not so good, but training on MS can bring improvement. I sincerely hope for your help.

**Comment by sconlyshootery** [comment]
Sorry, I didn't try on the Stereo data. This setting will not train posenet。

**Comment by sconlyshootery** [comment]
you can reopen it if you have further issues.
