### ISSUE TITLE
How to start non-distributed training

### ISSUE THREAD

**Issue by tushardmaske** [sconlyshootery/FeatDepth#78]
I want to start debugging code on pycharm. 
1) Debug wont start unless I stop running through distributed training. 
2) Also, I am getting errors of **RuntimeError: No rendezvous handler for env://** 

I just want to debug the code without torch.distributed mode on. Is there any way ?

**Comment by adizhol** [comment]
I got pycharm to enter debug with distributed mode by setting the script
that is debugged to be distributed.launch.py and all the parameters were
entered into the parameters field, including the train.py --config etc

**Comment by sconlyshootery** [comment]
you can reopen it if you have further issues.
