### ISSUE TITLE
Evaluation Issue

### ISSUE THREAD

**Issue by jwh97nn** [sconlyshootery/FeatDepth#87]
Hi, 

I have a similar concern with #17 for depth evaluation.

I'm using the pre-trained model for evaluation, which is provided from (2): `fm_depth.pth`.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/16673992/171128397-d6637418-af9f-4e00-a4f9-1324253ed843.png">
And the config file is `cfg_kitti_fm.py`, where all configurations remain the default.
Then I got the following result:
> -> Evaluating
using baseline
Scaling ratios | med: 37.681 | std: 0.061
abs_rel| sq_rel| rmse| rmse_log| a1| a2| a3| 
&0.099 &0.694 &4.427 &0.184 &0.890 &0.963 &0.982 \\

, which I think matches the result with trained on calibrated binocular videos in the paper.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/16673992/171130517-537f75bb-420b-47b1-8ef0-c63d0222e889.png">

But I cannot find the one trained on monocular videos only, with the following result mentioned in the paper:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/16673992/171131868-a40c1d50-3e7b-46d0-ac6b-7e77d1e1dfb5.png">

So,
1. I wonder if you could provide the model pre-trained on monocualr videos only for evaluation?
2. Just to make sure my implementent is right. Since your depth decoder is different from Monodepth2, so your model outputs disps with resolutions of `1/2, 1/4, 1/8, 1/16`, rather than `1, 1/2, 1/4, 1/8` which Monodepth2 does.

Hope to hear back from you.

**Comment by sconlyshootery** [comment]
I'm sorry that I don't save the model weights pre-trained on monocular videos, you might have to train the model.
