### ISSUE TITLE
Inverting pose for fame -1

### ISSUE THREAD

**Issue by adizhol** [sconlyshootery/FeatDepth#9]
Hello,

I have two related questions:
1. Does the PoseNet predict source-to-target or target-to-source relative pose?
2. Why do you invert the predicted pose of the -1 frame, and not invert the inputs to the PoseNet?

Thank you,
Adi

**Comment by sconlyshootery** [comment]
The inputs of posenet are in chronological order, this process will make it easy for posenet to predict relative pose.

**Comment by adizhol** [comment]
Thank you for the quick reply.
So the relative pose is frame(-1) to frame(0) or frame(0) to frame(-1)?

**Comment by sconlyshootery** [comment]
The output of posenet is -1 to 0, and this result will be transformed into 0 to -1 before used for warping source images.

**Comment by adizhol** [comment]
ok. thank you!
